---
# tasks file for postgresql-replication-master
- name: Create replication role
  postgresql_user:
    name: replication
    role_attr_flags: LOGIN,REPLICATION
  sudo_user: postgres

- name: Set replication parameters on postgre config
  lineinfile:
    dest: "{{ postgresql_config_file }}"
    regexp: '^({{ item.key }}\s*=).*'
    backrefs: yes
    line: '\1 {{ item.value }}'
    state: present
  with_items:
    - "{{ replication_config }}"

- name: Allow replication standby access
  lineinfile:
    dest: "{{ postgresql_hba_file }}"
    line: "hostssl	replication	all 	{{ item }}	trust"
    state: present
  with_items:
    - "{{ standby_definitions }}"
